// This file is automatically generated. Do not edit it directly.
import { createClient, type Session, type User } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const SEED_PRODUCTS = [
  {
    id: "voltcore-20000mah",
    name: "VoltCore 20000mAh Power Bank",
    description:
      "High-capacity 20,000mAh power bank with 22.5W fast charging, dual USB-A and USB-C PD. Charges most phones 4–5 times. Ideal for NEPA outages.",
    category: "power-banks",
    price: 18500,
    stock: 24,
    image_url: "/products/powerbank.jpg",
    featured: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "braided-usb-c-2m",
    name: "Braided USB-C Cable 2m",
    description:
      "Tough nylon-braided USB-C to USB-C cable, 65W fast charging and data transfer. Built to survive daily use.",
    category: "cables",
    price: 3200,
    stock: 80,
    image_url: "/products/cable.jpg",
    featured: true,
    created_at: "2025-01-02T00:00:00.000Z",
  },
  {
    id: "solar-inverter-1kva",
    name: "Solar Inverter 1kVA",
    description:
      "1kVA pure sine wave hybrid inverter with built-in MPPT solar charge controller. Powers TV, fans, lights and laptops.",
    category: "inverters-power-solutions",
    price: 124000,
    stock: 6,
    image_url: "/products/inverter.jpg",
    featured: true,
    created_at: "2025-01-03T00:00:00.000Z",
  },
  {
    id: "65w-gan-charger",
    name: "65W GaN USB-C Charger",
    description:
      "Compact GaN wall charger with 2 USB-C and 1 USB-A port. Fast-charges phones, tablets and laptops. UK 3-pin plug.",
    category: "chargers-adapters",
    price: 14500,
    stock: 30,
    image_url: "/products/charger.jpg",
    featured: true,
    created_at: "2025-01-04T00:00:00.000Z",
  },
  {
    id: "led-bulbs-9w",
    name: "LED Bulbs 9W (Pack of 10)",
    description:
      "Energy-saving 9W LED bulbs, cool daylight, E27 screw base. Bright light, low power usage.",
    category: "bulbs-lighting",
    price: 4800,
    stock: 50,
    image_url: "/products/bulbs.jpg",
    featured: false,
    created_at: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "13a-double-socket",
    name: "13A Double Socket Plate",
    description:
      "Durable 13A twin switched socket outlet with neon indicators. Standard UK/Nigeria fitting.",
    category: "sockets-extensions",
    price: 1500,
    stock: 120,
    image_url: "/products/socket.jpg",
    featured: false,
    created_at: "2025-01-06T00:00:00.000Z",
  },
  {
    id: "4-way-surge-extension",
    name: "4-Way Surge Extension",
    description: "4-gang extension box with surge protection, 2 USB ports and 3m heavy-duty cord.",
    category: "sockets-extensions",
    price: 6500,
    stock: 40,
    image_url: "/products/extension.jpg",
    featured: false,
    created_at: "2025-01-07T00:00:00.000Z",
  },
  {
    id: "2-5mm-copper-wire",
    name: "2.5mm Copper Wire (100m)",
    description: "Pure copper 2.5mm single-core cable, 100m coil. For house wiring and sockets.",
    category: "wires-electrical-materials",
    price: 38500,
    stock: 15,
    image_url: "/products/wire.jpg",
    featured: false,
    created_at: "2025-01-08T00:00:00.000Z",
  },
  {
    id: "dstv-gotv-lnb-remote",
    name: "DSTV/GOTV LNB & Remote Kit",
    description: "Universal single LNB with replacement DSTV/GOTV remote control. Easy setup.",
    category: "dstv-gotv-accessories",
    price: 6750,
    stock: 35,
    image_url: "/products/dstv.jpg",
    featured: true,
    created_at: "2025-01-09T00:00:00.000Z",
  },
  {
    id: "200w-solar-panel",
    name: "200W Solar Panel",
    description: "Monocrystalline 200W solar panel with high efficiency cells and aluminium frame.",
    category: "solar-products",
    price: 72000,
    stock: 10,
    image_url: "/products/solarpanel.jpg",
    featured: false,
    created_at: "2025-01-10T00:00:00.000Z",
  },
  {
    id: "rechargeable-led-lamp",
    name: "Rechargeable LED Lamp",
    description: "Portable rechargeable lamp with 3 brightness modes and up to 12 hours runtime.",
    category: "bulbs-lighting",
    price: 5500,
    stock: 45,
    image_url: "/products/lamp.jpg",
    featured: false,
    created_at: "2025-01-11T00:00:00.000Z",
  },
  {
    id: "clear-phone-case",
    name: "Clear Phone Case + Tempered Glass",
    description:
      "Shockproof clear case with 9H tempered glass screen protector. Available for popular Samsung, Tecno, Infinix and iPhone models.",
    category: "phone-accessories",
    price: 3500,
    stock: 100,
    image_url: "/products/phonecase.jpg",
    featured: true,
    created_at: "2025-01-12T00:00:00.000Z",
  },
  {
    id: "wireless-earbuds-pro",
    name: "Wireless Earbuds Pro",
    description:
      "Bluetooth 5.3 earbuds with charging case, deep bass and 24-hour total battery life.",
    category: "earphones-headsets",
    price: 12500,
    stock: 28,
    image_url: "/products/earbuds.jpg",
    featured: false,
    created_at: "2025-01-13T00:00:00.000Z",
  },
  {
    id: "circuit-breaker-32a",
    name: "Circuit Breaker 32A",
    description:
      "Single-pole 32A MCB for distribution boards. Protects against overload and short circuit.",
    category: "plugs-fuses-switches",
    price: 2800,
    stock: 60,
    image_url: "/products/breaker.jpg",
    featured: false,
    created_at: "2025-01-14T00:00:00.000Z",
  },
];

type MockRow = Record<string, unknown>;

const authListeners: Set<(event: string, session: unknown) => void> = new Set();
let mockCurrentSession: unknown = null;
if (typeof window !== "undefined") {
  try {
    const saved = localStorage.getItem("josppy_mock_session");
    if (saved) mockCurrentSession = JSON.parse(saved);
  } catch {
    // Ignore storage parse errors
  }
}

const ADMIN_EMAIL = "udojoshuasunday@gmail.com";
const ADMIN_UUID = "6e57d269-9db1-4268-887b-5506425fa728";
const ADMIN_UUID_LEGACY = "6e34907e-30a8-4ab9-870c-5d4e535abf21";

const inMemoryTables: Record<string, MockRow[]> = {
  products: [...SEED_PRODUCTS],
  orders: [],
  order_items: [],
  profiles: [
    {
      id: ADMIN_UUID,
      email: ADMIN_EMAIL,
      full_name: "Joshua Sunday",
      phone: "09061848821",
      address: "Victoria Island",
      state: "Lagos",
      city: "Lagos",
      created_at: "2025-01-01T00:00:00.000Z",
    },
    {
      id: ADMIN_UUID_LEGACY,
      email: ADMIN_EMAIL,
      full_name: "Joshua Sunday",
      phone: "09061848821",
      address: "Victoria Island",
      state: "Lagos",
      city: "Lagos",
      created_at: "2025-01-01T00:00:00.000Z",
    },
  ],
  user_roles: [
    {
      id: "role-admin-udojoshua",
      user_id: ADMIN_UUID,
      role: "admin",
    },
    {
      id: "role-user-udojoshua",
      user_id: ADMIN_UUID,
      role: "user",
    },
    {
      id: "role-admin-udojoshua-legacy",
      user_id: ADMIN_UUID_LEGACY,
      role: "admin",
    },
    {
      id: "role-user-udojoshua-legacy",
      user_id: ADMIN_UUID_LEGACY,
      role: "user",
    },
  ],
};

// Seed admin role for mock user ONLY if authenticated as the designated admin account
if (mockCurrentSession && typeof window !== "undefined") {
  try {
    const sessUser = (mockCurrentSession as { user?: { id: string; email?: string } })?.user;
    if (sessUser?.id && sessUser.email?.toLowerCase() === ADMIN_EMAIL) {
      if (
        !inMemoryTables["user_roles"].some(
          (r) => r["user_id"] === sessUser.id && r["role"] === "admin",
        )
      ) {
        inMemoryTables["user_roles"].push({
          id: `role-admin-${sessUser.id}`,
          user_id: sessUser.id,
          role: "admin",
        });
      }
    }
  } catch {
    // Ignore seed error
  }
}

interface MockQueryBuilder {
  select(_fields?: string): MockQueryBuilder;
  order(field: string, options?: { ascending?: boolean }): MockQueryBuilder;
  eq(field: string, value: unknown): MockQueryBuilder;
  maybeSingle(): Promise<{ data: MockRow | null; error: null }>;
  single(): Promise<{ data: MockRow | null; error: { message: string } | null }>;
  then<TResult1 = { data: MockRow[]; error: null }, TResult2 = never>(
    onFulfilled?:
      ((value: { data: MockRow[]; error: null }) => TResult1 | PromiseLike<TResult1>) | null,
    onRejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
  ): Promise<TResult1 | TResult2>;
}

function createMockQueryBuilder(items: MockRow[]): MockQueryBuilder {
  let currentItems = [...items];

  const builder: MockQueryBuilder = {
    select(_fields?: string) {
      return builder;
    },
    order(field: string, options?: { ascending?: boolean }) {
      const asc = options?.ascending !== false;
      currentItems.sort((a, b) => {
        const valA = a[field];
        const valB = b[field];
        if (typeof valA === "string" && typeof valB === "string") {
          return asc ? valA.localeCompare(valB) : valB.localeCompare(valA);
        }
        if (typeof valA === "number" && typeof valB === "number") {
          return asc ? valA - valB : valB - valA;
        }
        return 0;
      });
      return builder;
    },
    eq(field: string, value: unknown) {
      currentItems = currentItems.filter((item) => item[field] === value);
      return builder;
    },
    maybeSingle() {
      return Promise.resolve({
        data: currentItems[0] ?? null,
        error: null,
      });
    },
    single() {
      if (currentItems.length === 0) {
        return Promise.resolve({ data: null, error: { message: "Row not found" } });
      }
      return Promise.resolve({ data: currentItems[0] ?? null, error: null });
    },
    then(onFulfilled, onRejected) {
      return Promise.resolve({ data: currentItems, error: null }).then(onFulfilled, onRejected);
    },
  };

  return builder;
}

function notifyAuth(event: string, session: unknown) {
  mockCurrentSession = session;
  if (typeof window !== "undefined") {
    try {
      if (session) {
        localStorage.setItem("josppy_mock_session", JSON.stringify(session));
      } else {
        localStorage.removeItem("josppy_mock_session");
      }
    } catch {
      // Ignore storage errors
    }
  }
  for (const cb of authListeners) {
    try {
      cb(event, session);
    } catch {
      // Ignore listener error
    }
  }
}

function createMockSupabaseClient() {
  console.warn(
    "[AI Studio] Supabase environment variables not configured — using in-memory mock store with seed catalog.",
  );

  return {
    from(tableName: string) {
      if (!inMemoryTables[tableName]) {
        inMemoryTables[tableName] = [];
      }
      const tableData = inMemoryTables[tableName]!;

      return {
        select(_fields?: string) {
          return createMockQueryBuilder(tableData);
        },
        upsert(values: MockRow | MockRow[]) {
          const arr = Array.isArray(values) ? values : [values];
          for (const item of arr) {
            const existingIdx = tableData.findIndex((r) => r["id"] && r["id"] === item["id"]);
            if (existingIdx >= 0) {
              tableData[existingIdx] = { ...tableData[existingIdx], ...item };
            } else {
              tableData.push({
                created_at: new Date().toISOString(),
                ...item,
              });
            }
          }
          return {
            select() {
              return createMockQueryBuilder(arr);
            },
            then<TResult1 = { data: MockRow[]; error: null }, TResult2 = never>(
              onFulfilled?:
                | ((value: { data: MockRow[]; error: null }) => TResult1 | PromiseLike<TResult1>)
                | null,
              onRejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
            ) {
              return Promise.resolve({ data: arr, error: null }).then(onFulfilled, onRejected);
            },
          };
        },
        insert(values: MockRow | MockRow[]) {
          const arr = Array.isArray(values) ? values : [values];
          const inserted = arr.map((item) => ({
            id:
              typeof item["id"] === "string"
                ? item["id"]
                : `mock-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
            created_at: new Date().toISOString(),
            ...item,
          }));
          tableData.push(...inserted);
          if (tableName === "order_items") {
            const productsList = inMemoryTables["products"] ?? [];
            for (const item of inserted) {
              const prodId = item["product_id"];
              const qty = Number(item["quantity"]) || 1;
              const prod = productsList.find((p) => p["id"] === prodId);
              if (prod && typeof prod["stock"] === "number") {
                prod["stock"] = Math.max(0, (prod["stock"] as number) - qty);
              }
            }
          }
          return {
            select() {
              return createMockQueryBuilder(inserted);
            },
            then<TResult1 = { data: MockRow[]; error: null }, TResult2 = never>(
              onFulfilled?:
                | ((value: { data: MockRow[]; error: null }) => TResult1 | PromiseLike<TResult1>)
                | null,
              onRejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
            ) {
              return Promise.resolve({ data: inserted, error: null }).then(onFulfilled, onRejected);
            },
          };
        },
        update(updates: MockRow) {
          return {
            eq(field: string, val: unknown) {
              for (const row of tableData) {
                if (row[field] === val) {
                  Object.assign(row, updates);
                }
              }
              return Promise.resolve({ data: updates, error: null });
            },
          };
        },
        delete() {
          return {
            eq(field: string, val: unknown) {
              const idx = tableData.findIndex((r) => r[field] === val);
              if (idx >= 0) tableData.splice(idx, 1);
              return Promise.resolve({ data: null, error: null });
            },
          };
        },
      };
    },
    auth: {
      onAuthStateChange(cb: (event: string, session: unknown) => void) {
        authListeners.add(cb);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                authListeners.delete(cb);
              },
            },
          },
        };
      },
      getSession: async () => ({
        data: { session: mockCurrentSession as Session | null },
        error: null,
      }),
      getUser: async () => ({
        data: { user: ((mockCurrentSession as { user?: User })?.user as User) ?? null },
        error: null,
      }),
      signInWithPassword: async ({ email, password }: { email: string; password?: string }) => {
        if (!email) {
          return { data: { session: null, user: null }, error: new Error("Email is required") };
        }
        if (!password || password.length < 6) {
          return {
            data: { session: null, user: null },
            error: new Error("Password must be at least 6 characters."),
          };
        }

        let mockUsers: Record<string, { id: string; email: string; password?: string }> = {};
        if (typeof window !== "undefined") {
          try {
            const raw = localStorage.getItem("josppy_mock_users");
            if (raw) mockUsers = JSON.parse(raw);
          } catch {
            // Ignore parse error
          }
        }

        const normalizedEmail = email.trim().toLowerCase();
        const userCred = mockUsers[normalizedEmail];
        if (userCred && userCred.password && userCred.password !== password) {
          return {
            data: { session: null, user: null },
            error: new Error("Invalid login credentials. Please check your email and password."),
          };
        }

        const profiles = inMemoryTables["profiles"] ?? [];
        const existingProfile = profiles.find(
          (p) => (p["email"] as string)?.toLowerCase() === normalizedEmail,
        );
        const userId = userCred?.id || (existingProfile?.["id"] as string) || `user-${Date.now()}`;
        const user = {
          id: userId,
          email,
          user_metadata: {
            full_name: (existingProfile?.["full_name"] as string) || email.split("@")[0],
            phone: (existingProfile?.["phone"] as string) || "",
          },
          aud: "authenticated",
          role: "authenticated",
          created_at: new Date().toISOString(),
        };
        const session = {
          access_token: "mock-token-" + Date.now(),
          token_type: "bearer",
          user,
        };

        const userRoles = inMemoryTables["user_roles"] ?? [];
        const shouldBeAdmin = normalizedEmail === ADMIN_EMAIL;
        if (
          shouldBeAdmin &&
          !userRoles.some((r) => r["user_id"] === userId && r["role"] === "admin")
        ) {
          userRoles.push({ id: `role-${Date.now()}-admin`, user_id: userId, role: "admin" });
        }
        if (!userRoles.some((r) => r["user_id"] === userId && r["role"] === "user")) {
          userRoles.push({ id: `role-${Date.now()}-user`, user_id: userId, role: "user" });
        }

        notifyAuth("SIGNED_IN", session);
        return { data: { session, user }, error: null };
      },
      signUp: async ({
        email,
        password,
        options,
      }: {
        email: string;
        password?: string;
        options?: { data?: Record<string, unknown> };
      }) => {
        if (!email) {
          return { data: { session: null, user: null }, error: new Error("Email is required") };
        }
        if (!password || password.length < 6) {
          return {
            data: { session: null, user: null },
            error: new Error("Password must be at least 6 characters."),
          };
        }

        const normalizedEmail = email.trim().toLowerCase();
        let mockUsers: Record<string, { id: string; email: string; password?: string }> = {};
        if (typeof window !== "undefined") {
          try {
            const raw = localStorage.getItem("josppy_mock_users");
            if (raw) mockUsers = JSON.parse(raw);
          } catch {
            // Ignore parse error
          }
        }

        const profiles = inMemoryTables["profiles"] ?? [];
        const existingProfile = profiles.find(
          (p) => (p["email"] as string)?.toLowerCase() === normalizedEmail,
        );

        if (mockUsers[normalizedEmail] || existingProfile) {
          return {
            data: { session: null, user: null },
            error: new Error("User already registered with this email. Please sign in instead."),
          };
        }

        const userId = `user-${Date.now()}`;
        const meta = options?.data || {};
        const user = {
          id: userId,
          email,
          user_metadata: meta,
          aud: "authenticated",
          role: "authenticated",
          created_at: new Date().toISOString(),
        };
        const session = {
          access_token: "mock-token-" + Date.now(),
          token_type: "bearer",
          user,
        };

        // Save credential
        mockUsers[normalizedEmail] = { id: userId, email, password };
        if (typeof window !== "undefined") {
          try {
            localStorage.setItem("josppy_mock_users", JSON.stringify(mockUsers));
          } catch {
            // Ignore storage error
          }
        }

        // Save profile
        profiles.push({
          id: userId,
          email,
          full_name: (meta["full_name"] as string) || "",
          phone: (meta["phone"] as string) || "",
          address: "",
          state: "Lagos",
          city: "",
          created_at: new Date().toISOString(),
        });
        if (typeof window !== "undefined") {
          try {
            localStorage.setItem("josppy_mock_profiles", JSON.stringify(profiles));
          } catch {
            // Ignore storage error
          }
        }

        // Customer user roles - DO NOT automatically make every newly registered customer an admin!
        const userRoles = inMemoryTables["user_roles"] ?? [];
        const shouldBeAdmin = normalizedEmail === ADMIN_EMAIL;
        if (
          shouldBeAdmin &&
          !userRoles.some((r) => r["user_id"] === userId && r["role"] === "admin")
        ) {
          userRoles.push({ id: `role-${Date.now()}-admin`, user_id: userId, role: "admin" });
        }
        if (!userRoles.some((r) => r["user_id"] === userId && r["role"] === "user")) {
          userRoles.push({ id: `role-${Date.now()}-user`, user_id: userId, role: "user" });
        }
        if (typeof window !== "undefined") {
          try {
            localStorage.setItem("josppy_mock_user_roles", JSON.stringify(userRoles));
          } catch {
            // Ignore storage error
          }
        }

        notifyAuth("SIGNED_IN", session);
        return { data: { session, user }, error: null };
      },
      signOut: async () => {
        notifyAuth("SIGNED_OUT", null);
        return { error: null };
      },
    },
    storage: {
      from(bucket: string) {
        return {
          getPublicUrl: (path: string) => ({ data: { publicUrl: path } }),
          upload: async (path: string, file: File | Blob) => {
            let dataUrl = "";
            if (typeof FileReader !== "undefined") {
              try {
                dataUrl = await new Promise<string>((resolve) => {
                  const reader = new FileReader();
                  reader.onload = () => resolve(reader.result as string);
                  reader.readAsDataURL(file);
                });
              } catch {
                dataUrl = `/products/${path}`;
              }
            } else {
              dataUrl = `/products/${path}`;
            }
            return {
              data: { path, fullPath: `${bucket}/${path}`, url: dataUrl },
              error: null,
            };
          },
        };
      },
    },
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_URL"]) ||
    (typeof process !== "undefined" ? process.env?.["SUPABASE_URL"] : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"]) ||
    (typeof process !== "undefined" ? process.env?.["SUPABASE_PUBLISHABLE_KEY"] : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
